language: node_js
os:
  - linux
dist:
  - trusty
node_js:
  - '10'
notifications:
  email: false
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run coverage
after_success:
  - npm run report-coverage
